import type { FinalSummaryViewModel } from '@ui/review/types.ts'

export const MOCK_FINAL_SUMMARY: FinalSummaryViewModel = {
  programmeDayLabel: 'DEN 29',
  weeks: [
    {
      weekNo: 1,
      status: 'PREKROCENO',
      timeUsedLabel: '9h 30 min',
      timeLimitLabel: '10h 0 min',
      stakesUsedLabel: '8 640 Kč',
      stakesLimitLabel: '8 000 Kč',
      filledDays: 6,
      totalDays: 7,
      days: [
        { dayLabel: 'ÚT', dayNumber: 1, state: 'completed' },
        { dayLabel: 'ST', dayNumber: 2, state: 'completed' },
        { dayLabel: 'ČT', dayNumber: 3, state: 'missing' },
        { dayLabel: 'PÁ', dayNumber: 4, state: 'completed' },
        { dayLabel: 'SO', dayNumber: 5, state: 'completed' },
        { dayLabel: 'NE', dayNumber: 6, state: 'completed' },
        { dayLabel: 'PO', dayNumber: 7, state: 'missing' },
      ],
    },
    {
      weekNo: 2,
      status: 'POZOR',
      timeUsedLabel: '7h 10 min',
      timeLimitLabel: '8h 0 min',
      stakesUsedLabel: '6 900 Kč',
      stakesLimitLabel: '8 000 Kč',
      filledDays: 7,
      totalDays: 7,
      days: [
        { dayLabel: 'ÚT', dayNumber: 8, state: 'completed' },
        { dayLabel: 'ST', dayNumber: 9, state: 'completed' },
        { dayLabel: 'ČT', dayNumber: 10, state: 'completed' },
        { dayLabel: 'PÁ', dayNumber: 11, state: 'completed' },
        { dayLabel: 'SO', dayNumber: 12, state: 'completed' },
        { dayLabel: 'NE', dayNumber: 13, state: 'completed' },
        { dayLabel: 'PO', dayNumber: 14, state: 'completed' },
      ],
    },
    {
      weekNo: 3,
      status: 'POZOR',
      timeUsedLabel: '6h 40 min',
      timeLimitLabel: '7h 30 min',
      stakesUsedLabel: '7 300 Kč',
      stakesLimitLabel: '8 000 Kč',
      filledDays: 7,
      totalDays: 7,
      days: [
        { dayLabel: 'ÚT', dayNumber: 15, state: 'completed' },
        { dayLabel: 'ST', dayNumber: 16, state: 'completed' },
        { dayLabel: 'ČT', dayNumber: 17, state: 'completed' },
        { dayLabel: 'PÁ', dayNumber: 18, state: 'completed' },
        { dayLabel: 'SO', dayNumber: 19, state: 'completed' },
        { dayLabel: 'NE', dayNumber: 20, state: 'completed' },
        { dayLabel: 'PO', dayNumber: 21, state: 'completed' },
      ],
    },
    {
      weekNo: 4,
      status: 'OK',
      timeUsedLabel: '4h 0 min',
      timeLimitLabel: '7h 0 min',
      stakesUsedLabel: '3 200 Kč',
      stakesLimitLabel: '8 000 Kč',
      filledDays: 7,
      totalDays: 7,
      days: [
        { dayLabel: 'ÚT', dayNumber: 22, state: 'completed' },
        { dayLabel: 'ST', dayNumber: 23, state: 'completed' },
        { dayLabel: 'ČT', dayNumber: 24, state: 'completed' },
        { dayLabel: 'PÁ', dayNumber: 25, state: 'completed' },
        { dayLabel: 'SO', dayNumber: 26, state: 'completed' },
        { dayLabel: 'NE', dayNumber: 27, state: 'completed' },
        { dayLabel: 'PO', dayNumber: 28, state: 'completed' },
      ],
    },
  ],
}
