/**
 * Hands generated bytes to the browser's download mechanism.
 *
 * Kept separate from any component so the export flow stays testable and the
 * DOM poking lives in exactly one place.
 */
export function downloadBytes(bytes: Uint8Array, filename: string, mimeType: string): void {
  const url = URL.createObjectURL(new Blob([bytes as BlobPart], { type: mimeType }))
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  // Safari only honours `download` for an anchor that is in the document.
  document.body.append(anchor)
  anchor.click()
  anchor.remove()
  // Revoking synchronously cancels the download in Safari, so let the click
  // settle first.
  setTimeout(() => {
    URL.revokeObjectURL(url)
  }, 0)
}

/** `nudz-export-2026-08-16.zip` — dated so repeated exports don't overwrite. */
export function exportFilename(now: Date): string {
  const year = String(now.getFullYear())
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  return `nudz-export-${year}-${month}-${day}.zip`
}
